[package]
name = "IBKR-API-Rust"
version = "0.1.0"
authors = ["bmiller3230"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
name = "twsapi"
path = "src/lib.rs"

[[bin]]
name = "twsapi_client"
path = "src/bin.rs"

[dependencies]
log = "0.4.6"
log4rs = "0.8.1"
bytebuffer = "0.2.1"
encoding = "0.2"
# error-chain = "0.12.1"
num = "0.2"
num-derive = "0.3"
num-traits = "0.2"
serde = "1.0.104"
byteorder = "1.3.2"
ascii = "1.0.0"
from-ascii = "0.0.1"